[package]
name = "RustBrawl"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4.42"
colored = "3.0.0"
lazy_static = "1.5.0"
regex = "1.12.2"
rustyline = "17.0.2"
tokio = "1.48.0"
# No dependencies for now
